### ISSUE TITLE
Please add python environment to be made in python 3.7.

### ISSUE THREAD

**Issue by nimit2801** [SarthakRana/Covid-19-Dashboard#5]
### This is an error @ streamlit communities end.

https://github.com/streamlit/streamlit/issues/1756
![image](https://user-images.githubusercontent.com/53462249/95111533-41123f80-075d-11eb-91bc-9ae68b40142f.png)

**Comment by SarthakRana** [comment]
I used python 3.8 (3.8.3 to be exact). Didn't find any issue with Streamlit once.
Share with me the link for this.

**Comment by nimit2801** [comment]
This happened when I was installing all the requirements it gave me a big error, again I tried to manually install it all the requirements one-by-one then streamlit gave me an error.

**Comment by g-o-o-g-l-e** [comment]
but I am using 3.10

**Comment by g-o-o-g-l-e** [comment]
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\#####\\Py
charmProjects\\1stPrj\\.venv\\Scripts\\streamlit.exe' -> 'C:\\Users\\ethan\\PycharmProjects\\1stPrj\\.venv\\Scripts\\streamlit.exe.deleteme'
Check the permissions.
